### ISSUE TITLE
This cant be installed as an extension in auth0? 

### ISSUE THREAD

**Issue by nemccarthy** [auth0-extensions/auth0-logs-to-segment#3]
The link to install as an extension in Auth0 doesnt work and it looks like its not in the list of extensions on the Auth0 dashboard?

**Comment by tandrup** [comment]
I'm also having trouble installing it

**Comment by tandrup** [comment]
Guess the whole repo is stale 😞

**Comment by tandrup** [comment]
Yo bot. Guess you can mark the whole repo as stale 👎

**Comment by fyockm** [comment]
@tandrup the Logs to Segment extension was just published to the Auth0 Extension Gallery. Also note that the code has been moved to [auth0-logs-to-provider](https://github.com/auth0-extensions/auth0-logs-to-provider). See https://github.com/auth0-extensions/auth0-logs-to-segment/pull/7
